# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d004742b6a21a201b5deb69e90d967b29aea9ebc46c72fe59a806ce985b73fae2891adab5d30e7f895d6a37b437398365bb3a21099ca8037c5665fe9dc5907e8

test:
  secret_key_base: 9015bc5cf5aabd31bf8b4b10554cfc4369528b98be09779871522bbecb1c22e9f44504a0fb61c344941e326abeaad228bfc9df7203bc74ee99a2abccae740214

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
